import { useState } from 'react';
import type { GameState } from '../../simulation/types';
import { grossMargin, monthlyArr, monthlyBurn, monthlyCompanyOperations, monthlyCompute, monthlyPayroll, monthlyProductOperations, monthlyRent, runwayMonths, valuationOf } from '../../simulation/derived';
import { useGame } from '../../state/store';
import { money, pct } from '../format';
import { CharacterPortrait } from '../shared/CharacterPortrait';
import { lookFromSeed } from '../../simulation/look';
import { GameButton } from '../shared/controls';
export function FinancePanel({game}:{game:GameState}) {
  const [metric,setMetric]=useState<'cash'|'revenue'|'burn'>('cash');
  const history=game.history,values=history.map(p=>p[metric]),max=Math.max(1,...values),min=Math.min(0,...values);
  const path=values.map((v,i)=>`${i===0?'M':'L'} ${30+i*660/Math.max(1,values.length-1)} ${160-(v-min)/(max-min)*140}`).join(' ');
  const run=runwayMonths(game);
  const breakdown=game.company.lastMonthlyBreakdown;
  const lastNet=breakdown.revenue-breakdown.inference-breakdown.productOperations-breakdown.payroll-breakdown.office-breakdown.fixedCompute-breakdown.companyOperations;
  const hasStatement=Object.values(breakdown).some(value=>Math.abs(value)>0);
  const expectedCosts=monthlyPayroll(game)+monthlyRent(game)+monthlyCompute(game)+monthlyProductOperations(game)+monthlyCompanyOperations(game);
  const statementRows=[['Revenue',breakdown.revenue],['Payroll',-breakdown.payroll],['Inference',-breakdown.inference],['GTM, support & maintenance',-breakdown.productOperations],['Office',-breakdown.office],['Reserved compute',-breakdown.fixedCompute],['Company operations',-breakdown.companyOperations]] as const;
  return <div className="finance-ledger">
    <div className="ledger-top"><div><span className="eyebrow">Statement of the company</span><h3>The numbers that buy you time.</h3></div><span>{game.clock.date.year} / {String(game.clock.date.month).padStart(2,'0')}</span></div>
    <div className="ledger-metrics">{[['Cash',money(game.company.cash)],['Monthly revenue',money(monthlyArr(game))],['Net burn / month',money(monthlyBurn(game))],['Runway',run>=99?'Profitable':`${run.toFixed(1)} mo`],['Gross margin',pct(grossMargin(game)*100)]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>
    {hasStatement&&<details className="cash-breakdown"><summary><span>Last month’s cash change</span><strong className={lastNet>=0?'positive':'negative'}>{lastNet>=0?'+':''}{money(lastNet)}</strong></summary><div>{statementRows.filter(([,value])=>Math.abs(value)>0).map(([label,value])=><div className="ledger-row" key={label}><span>{label}</span><strong className={value>=0?'positive':'negative'}>{value>=0?'+':''}{money(value)}</strong></div>)}</div></details>}
    <div className="ledger-chart"><div className="choice-row">{(['cash','revenue','burn'] as const).map(k=><button key={k} aria-pressed={metric===k} onClick={()=>setMetric(k)}>{k}</button>)}</div>{history.length<2?<div className="chart-empty">Your first monthly statements will appear here as company time passes.</div>:<><svg viewBox="0 0 720 190" role="img" aria-label={`${metric} history from ${history.length} monthly reports`}><path d="M30 20H690M30 90H690M30 160H690" stroke="#d4d7c6" fill="none"/><path d={path} stroke="#547768" strokeWidth="2.5" fill="none"/>{values.map((v,i)=><circle key={i} cx={30+i*660/Math.max(1,values.length-1)} cy={160-(v-min)/(max-min)*140} r="3" fill="#b87648"><title>{history[i]!.year}-{history[i]!.month}: {money(v)}</title></circle>)}</svg><div className="chart-labels"><span>{history[0]!.year}-{history[0]!.month}</span><span>{money(max)} peak</span><span>{history.at(-1)!.year}-{history.at(-1)!.month}</span></div></>}</div>
    <div className="ledger-columns"><section><h4>Monthly expenses</h4>{[['People',monthlyPayroll(game)],['Office rent',monthlyRent(game)],['Compute & inference',monthlyCompute(game)],['GTM, support & maintenance',monthlyProductOperations(game)],['Management complexity',monthlyCompanyOperations(game)]].map(([label,value])=><div className="ledger-row" key={label}><span>{label}</span><strong>{money(Number(value))}</strong></div>)}<div className="ledger-row total"><span>Total expected costs</span><strong>{money(expectedCosts)}</strong></div></section><section><h4>Who owns the company</h4><div className="ownership-bar">{Object.entries(game.company.ownership).map(([k,v],i)=><i key={k} style={{width:`${v*100}%`,background:['#456a5a','#8aa888','#bf9c6a','#ad7155'][i]}}/>)}</div>{Object.entries(game.company.ownership).map(([k,v])=><div className="ledger-row" key={k}><span>{k}</span><strong>{pct(v*100)}</strong></div>)}</section></div>
    <div className="board-summary"><span className="eyebrow">The boardroom</span>{game.board?<p>{game.board.members.join(', ')} · Approval {pct(game.board.approval)} · {game.board.pressure} mandate · Monthly revenue target {money(game.board.arrTarget)}</p>:<p>Founder-led. No institutional board.</p>}<small>Estimated company value {money(valuationOf(game))}</small></div>
  </div>;
}
export function FundingPanel({game}:{game:GameState}) {
  const dispatch=useGame(s=>s.dispatch);
  return <div className="funding-workspace"><div className="workspace-intro"><div><span className="eyebrow">Raise capital / Keep perspective</span><h3>More runway. More opinions.</h3></div><GameButton data-tutorial="funding-meetings" tone="primary" disabled={game.funding.cooldownDays>0} title={game.funding.cooldownDays?`Next round in ${game.funding.cooldownDays} days`:'Meet three investors'} onClick={()=>dispatch({type:'generateFunding'})}>{game.funding.cooldownDays?`Available in ${game.funding.cooldownDays}d`:'Take meetings'}</GameButton></div>{!game.funding.offers.length&&<div className="empty-state"><h3>Keep a seat at your own table.</h3><p>Each term sheet trades cash for ownership. Institutional funding adds a board with growth expectations.</p></div>}<div className="term-sheets">{game.funding.offers.map((o,i)=><article className="investor-sheet" key={o.id}><div className="dossier-heading"><span>CONFIDENTIAL / {o.round.toUpperCase()}</span><span>0{i+1}</span></div><CharacterPortrait look={lookFromSeed(o.investor,o.archetype)}/><h3>{o.investor}</h3><p>{o.notes}</p><div className="investment-amount">{money(o.cash)}<small>Investment</small></div><dl><div><dt>Pre-money valuation</dt><dd>{money(o.valuation)}</dd></div><div><dt>New investor ownership</dt><dd>{pct(o.dilution*100)}</dd></div><div><dt>Your remaining stake</dt><dd>{pct(game.company.ownership.founder*(1-o.dilution)*100)}</dd></div></dl><p className="terms-consequence">One board seat. Quarterly reviews. Revenue targets rise with the next round.</p><GameButton tone="primary" onClick={()=>dispatch({type:'acceptOffer',offerId:o.id})}>Sign term sheet</GameButton></article>)}</div></div>;
}
