import { findRecipe, recipeKey } from '../../../data/recipes';
import type { Part, PartKind } from './Parts';

const p = (kind:PartKind,x=0,z=0,scale=1,y=0,yaw=0):Part => ({kind,at:[x,y,z],scale,yaw});
export interface ProductDesign { concept:string; parts:readonly Part[] }
const d = (concept:string,...parts:Part[]):ProductDesign => ({concept,parts});

/** Pair IDs, not display names: the duplicate legal/writing recipe retains its first-match identity. */
export const recipeDesigns:Record<string,ProductDesign> = {
  'chat.writing':d('Copy desk with assistant terminal and manuscript',p('printer',-.47,-.1),p('terminal',.48,-.15,.67),p('document',.4,.45,.75)),
  'chat.search':d('Document search scanner with answer display',p('scanner',-.47),p('terminal',.53,-.15,.8),p('document',.55,.48,.6)),
  'chat.code':d('Developer laptop and dedicated copilot sidecar',p('laptop',-.3,.1,1.2),p('phone',.65,-.16,.85)),
  'chat.memory':d('Personal conversation device with a keepsake archive',p('speaker',-.38,0,1.25),p('portrait',.42,.05,.75),p('book',.3,.5,.7)),
  'agent.browser':d('Autonomous multi-tab research station',p('browser',-.48,-.12,.95,.0,.18),p('browser',.46,-.2,.75,0,-.3),p('chip',.4,.42,.7)),
  'agent.workflow':d('Operations control board and document dispatch',p('board',-.3,-.2,1.1),p('printer',.62,.18,.8),p('package',-.5,.5,.6)),
  'agent.voice':d('Reception counter with telephone and appointment book',p('archive',-.5,0,.8),p('phone',-.5,0,.7,.88),p('headset',.45,.13),p('document',.43,.4,.6)),
  'avatar.video':d('Digital presenter on a portrait set with camera',p('portrait',-.28,-.13,1.25),p('camera',.66,.35,.85,0,-.4)),
  'chat.image':d('Illustration easel with conversational art director',p('easel',-.4),p('phone',.56,.16,.9)),
  'chat.retrieval':d('Office archive with a talking reference terminal',p('archive',-.47,-.1,1.15),p('terminal',.54,.15,.85),p('document',-.38,.5,.7)),
  'agent.code':d('Build server feeding a software shipping line',p('rack',-.68,-.12),p('conveyor',.35,.3,.95),p('package',.47,.3,.55,.46),p('code',.42,-.35,.7)),
  'reasoning.science':d('Microscope and analytical hypothesis board',p('microscope',-.52,.17,1.3),p('board',.47,-.25,.95)),
  'biology.science':d('Assay bench with tubes and microscope',p('cart',0,0,1.5),p('tubes',-.3,0,.7,1.16),p('microscope',.44,0,.65,1.16)),
  'agent.robotics':d('Wheeled floor worker delivering a parcel',p('robot',-.3,0,1.3),p('cart',.63,.25,.85),p('package',.63,.25,.55,.66)),
  'defense.robotics':d('Mobile perimeter inspection rover',p('rover',0,0,1.05),p('camera',-.22,-.08,.9,.49),p('chip',.42,.05,.6,.49)),
  'api.reasoning':d('Compute gateway with a reasoning console',p('rack',-.4,0,1.1),p('code',.53,.25,.8)),
  'code.opensource':d('Shared coding bench with open reference books',p('laptop',-.42,.2),p('code',.47,-.2,.8),p('book',.56,.47,.7)),
  'ads.chat':d('Sponsored answer kiosk and advertising placard',p('phone',-.36,.2,1.3),p('board',.51,-.24,.85)),
  'chat.education':d('Study desk with books and conversational tutor',p('openBook',-.52,.27,1.1),p('terminal',.34,-.13),p('document',.42,.5,.65)),
  'health.retrieval':d('Clinical records trolley with chart screen',p('cart',-.38,0,1.2),p('scanDisplay',-.38,0,.65,.93),p('archive',.62,-.13,.9)),
  'legal.writing':d('Contract printer with signed document and law volume',p('printer',-.32,-.1,1.25),p('book',.65,.15,.8),p('document',.65,.15,.75,.16)),
  'agent.finance':d('Treasury vault with transaction terminal',p('safe',-.45,-.1,1.2),p('laptop',.6,.3,.85)),
  'avatar.social':d('Network of portrait terminals around a shared hub',p('portrait',-.62,-.07,.68,0,.35),p('portrait',0,-.28,1),p('portrait',.63,.12,.68,0,-.35)),
  'analytics.workflow':d('Metrics wall paired with an operations dispatch printer',p('chart',-.42,-.17,1.15),p('printer',.65,.18,.8),p('document',-.55,.48,.7)),
  'agent.memory':d('Executive organizer with calendar and retained files',p('archive',-.58,-.15),p('board',.45,-.23,.9),p('phone',.43,.38,.7)),
  'analytics.search':d('Query analysis scanner and charting station',p('chart',-.47,-.16,.95),p('scanner',.51,.12,.86)),
  'ads.image':d('Campaign print studio with artwork and output press',p('easel',-.5,-.1),p('printer',.51,.28,1.05)),
  'chat.voice':d('Call-center headset, conversation screen and microphone',p('headset',-.52,.13,1.1),p('terminal',.45,-.2,.85),p('mic',.62,.46,.6)),
  'agent.computer-use':d('Unattended desktop with robotic input control',p('laptop',-.4,.18,1.1),p('arm',.6,-.18,.85,0,-.8)),
  'agent.security':d('Security operations console with secured event recorder',p('chart',-.53,-.1),p('safe',.54,.05,.9),p('camera',.54,.05,.65,.86)),
  'entertainment.video':d('Continuous production stage with camera and viewing seat',p('image',0,-.35,1.3),p('camera',-.62,.35,.75),p('seat',.55,.42,.7)),
  'entertainment.recommend':d('Home media console selecting the next show',p('image',-.38,-.1,1.1),p('speaker',.63,-.03),p('phone',.2,.48,.55)),
  'api.data':d('Licensed data archive feeding a network server',p('archive',-.44,0,1.1),p('rack',.49,.12,.9),p('document',0,.53,.6)),
  'hardware.reasoning':d('Desk-sized inference accelerator appliance',p('chip',0,.1,1.8),p('rack',-.48,-.35,.55)),
  'robotics.world-model':d('General-purpose robot with a physical training world',p('robot',-.48,-.1,1.45),p('terrain',.52,.3,.7)),
  'auto-research.self-improve':d('Robot experiment station with feedback compute',p('cart',-.25,0,1.4),p('arm',-.48,-.15,.9,1.08),p('tubes',.26,.08,.65,1.08),p('rack',.72,-.2,.8)),
  'defense.vision':d('Raised optical surveillance post',p('tower',-.15,0,.9),p('camera',-.15,0,.85,1.08),p('terminal',.61,.32,.6)),
  'agent.commerce':d('Shopping assistant at a parcel pickup counter',p('booth',-.3,-.08,1.05),p('robot',.64,.3,.7),p('package',-.3,.12,.55,.85)),
  'agent.education':d('Teaching board with learner seats and tablet',p('board',0,-.32,1.2),p('seat',-.56,.46,.75),p('seat',.51,.46,.75),p('phone',.71,-.1,.65)),
  'health.vision':d('Diagnostic scanner with radiology display',p('medicalScanner',-.47,.02,1.05),p('scanDisplay',.62,-.14,.9)),
  'agent.legal':d('Document discovery archive with automated sorter',p('archive',-.66,-.14,1.15),p('conveyor',.31,.34,.95),p('document',.35,.34,.65,.47),p('arm',.56,-.25,.7)),
  'analytics.finance':d('Trader risk workstation with paired chart screens',p('chart',-.52,-.13,1,0,.2),p('chart',.5,-.13,1,0,-.2),p('laptop',0,.48,.65)),
  'api.opensource':d('Shared server hosting public code',p('rack',-.58,-.1,1.15),p('rack',.07,-.12,.75),p('book',.62,.38),p('code',.58,.02,.62)),
  'analytics.chat':d('Desktop metrics explainer with voice sidecar',p('chart',-.22,-.07,1.25),p('speaker',.66,.18,.75)),
  'code.search':d('Repository inspection terminal and code archive',p('code',-.4,-.1,1.15),p('archive',.6,.11,.8),p('scanner',.6,.11,.55,.88)),
  'commerce.image':d('Product photography lightbox and catalog camera',p('booth',-.28,-.12),p('package',-.28,.04,.64,.81),p('camera',.65,.42,.8)),
  'education.voice':d('Language practice listening station and workbook',p('headset',-.4,-.06,1.3),p('book',.48,.21,1.1),p('mic',.58,-.2,.65)),
  'memory.social':d('Personal address archive with portrait and keepsake album',p('archive',-.4,-.1),p('portrait',-.4,-.1,.7,1.1),p('book',.53,.26)),
  'legal.retrieval':d('Case-law library and balance scales',p('archive',-.47,-.15,1.2),p('scales',.5,.2,.9),p('book',.5,.25,.75,.11)),
  'agent.science':d('Scheduled sample-handling instrument',p('conveyor',-.12,.26,1.3),p('tubes',-.25,.26,.8,.59),p('arm',.49,-.23,1.1)),
  'finance.simulation':d('Economic tabletop model with forecast screen',p('terrain',-.36,.19,1.05),p('chart',.6,-.27,.85)),
  'defense.simulation':d('Tactical simulation table and observation console',p('terrain',0,.19,1.4),p('camera',-.62,-.4,.8),p('laptop',.58,-.34,.6)),
  'ads.recommend':d('Advertising exchange with ranked placements',p('board',-.53,-.12),p('phone',.42,.23,1.1),p('rack',.77,-.3,.55)),
  'browser.search':d('Open web reading terminal with document scanner',p('laptop',-.51,.27),p('scanner',.51,-.11,.9)),
  'legal.workflow':d('Compliance filing station with checklist',p('board',-.42,-.2,1.05),p('archive',.6,.1,.95),p('document',-.43,.44,.8)),
  'avatar.education':d('Digital lecturer behind a lectern',p('portrait',0,-.27,1.3),p('lectern',0,.28,.8),p('openBook',0,.28,.65,.86)),
  'education.video':d('Course recording set with lesson board and camera',p('board',-.35,-.27,1.15),p('camera',.65,.3,.95),p('book',-.44,.43,.8)),
  'health.robotics':d('Clinical delivery robot with sample cart',p('clinicalRobot',-.25,-.08,1.35),p('tubes',.64,.24,.8)),
  'commerce.robotics':d('Warehouse picking arm and packing conveyor',p('arm',-.63,-.18,1.2),p('conveyor',.32,.26,1.1),p('package',.43,.26,.85,.51)),
  'security.vision':d('Camera anomaly recorder with monitoring screen',p('camera',-.49,.02,1.1),p('rack',.53,-.14,.9),p('scanDisplay',.53,-.14,.65,1.08)),
  'biology.data':d('Specimen archive with assay rack',p('freezer',-.4,-.15,1.15),p('tubes',.57,.3),p('document',.5,-.2,.7)),
  'api.voice':d('Speech gateway with recording microphone',p('rack',-.4,-.06,1.15),p('mic',.52,.2,1.1)),
  'image.opensource':d('Shared illustration easel with open source workstation',p('easel',-.44,-.12,1.1),p('laptop',.57,.35,.8)),
  'code.self-improve':d('Developer test rig with tuning arm',p('code',-.48,-.17,1.05),p('chip',.42,.29,1.1),p('arm',.63,-.28,.75)),
  'auto-research.biology':d('Automated wet-lab sampling line',p('conveyor',0,.22,1.35),p('tubes',-.37,.22,.8,.61),p('microscope',.44,-.3,.85),p('arm',.68,.44,.8)),
  'simulation.world-model':d('Physical sandbox city on a compute plinth',p('terrain',0,.1,1.6),p('rack',-.68,-.34,.52)),
  'analytics.hardware':d('Data-center rack with power-analysis console',p('rack',-.4,-.15,1.35),p('chart',.65,.28,.85)),
  'chat.entertainment':d('Interactive story player with open book and speaker',p('book',-.36,.26,1.3),p('speaker',.58,-.03,1.1),p('portrait',-.43,-.3,.75)),
  'ads.writing':d('Copy printing press with campaign placard',p('printer',-.43,.18,1.2),p('board',.54,-.24,.85)),
  'health.search':d('Clinical search station with diagnostic probe',p('scanDisplay',-.43,-.12,1.1),p('microscope',.58,.2,.95),p('document',-.5,.5,.7)),
  'ads.agent':d('Campaign purchasing console with placement board',p('laptop',-.51,.25,1.05),p('board',.5,-.24),p('phone',.76,.42,.55)),
  'legal.reasoning':d('Counsel desk with legal balance and reference terminal',p('scales',-.48,.07,1.1),p('terminal',.55,-.17,.9),p('book',.5,.46,.8)),
  'code.reasoning':d('Senior engineer design-review board and workstation',p('board',-.4,-.33,1.1),p('laptop',.4,.36,1.1),p('rack',.73,-.25,.65)),
  'health.memory':d('Long-term patient record station with scan archive',p('archive',-.46,-.1,1.15),p('scanDisplay',.55,.1),p('book',.5,.5,.65)),
  'browser.commerce':d('Comparison-shopping terminal beside a parcel stack',p('browser',-.46,-.12,1.1),p('package',.58,.16,.95),p('package',.58,.16,.65,.48)),
  'computer-use.finance':d('Legacy finance workstation with mechanical operator',p('laptop',-.5,.2,1.05),p('safe',.58,-.22,.8),p('arm',.58,-.22,.7,.77)),
};

export const primitiveDesigns:Record<string,ProductDesign> = {
  chat:d('Conversation terminal',p('phone',0,0,1.5)),
  writing:d('Manuscript and pen',p('document',0,0,1.8)),
  search:d('Optical document search',p('scanner',0,0,1.35)),
  image:d('Illustration easel',p('easel',0,0,1.3)),
  code:d('Developer laptop',p('laptop',0,0,1.5)),
  voice:d('Studio microphone',p('mic',0,0,1.5)),
  video:d('Production camera',p('camera',0,0,1.5)),
  avatar:d('Digital portrait display',p('portrait',0,0,1.5)),
  memory:d('Persistent storage cabinet',p('archive',0,0,1.4)),
  retrieval:d('Archive document reader',p('archive',-.4,0),p('scanner',.53,.2,.8)),
  reasoning:d('Problem-solving board and notebook',p('board',-.1,-.15,1.2),p('document',.2,.5)),
  agent:d('Autonomous control station',p('terminal',-.27,-.1,1.1),p('chip',.6,.33,.75)),
  browser:d('Tabbed web terminal',p('browser',0,0,1.5)),
  'computer-use':d('Computer and robotic input device',p('laptop',-.38,.18),p('arm',.6,-.2)),
  workflow:d('Document dispatch line',p('printer',-.55,-.12),p('conveyor',.36,.3)),
  analytics:d('Chart display',p('chart',0,0,1.5)),
  simulation:d('Tabletop simulation',p('terrain',0,0,1.7)),
  recommend:d('Media selection console',p('phone',-.42,.23,1.2),p('speaker',.42,-.1,1.2)),
  security:d('Secure appliance',p('safe',0,0,1.5)),
  robotics:d('Industrial robot arm',p('arm',0,0,1.5)),
  vision:d('Computer vision scanning rig',p('scanner',-.3,0,1.2),p('camera',.5,.1,.65)),
  'world-model':d('World simulation and observer',p('terrain',-.25,.2,1.3),p('scanDisplay',.57,-.27,.8)),
  science:d('Laboratory microscope',p('microscope',0,0,1.65)),
  biology:d('Specimen assay rack',p('tubes',0,0,1.9)),
  finance:d('Treasury ledger and safe',p('safe',-.35,-.1,1.1),p('book',.58,.32)),
  defense:d('Observation tower',p('tower',0,0),p('camera',0,0,.8,1.2)),
  education:d('Open learning books',p('openBook',0,0,1.6),p('book',-.5,-.3,.7)),
  health:d('Clinical diagnostic trolley',p('cart',0,0,1.5),p('scanDisplay',0,0,.8,1.17)),
  entertainment:d('Screening room',p('image',0,-.3,1.2),p('seat',.4,.45,.85)),
  social:d('Paired conversation portraits',p('portrait',-.5,0,1,0,.2),p('portrait',.5,0,1,0,-.2)),
  ads:d('Campaign poster',p('board',0,0,1.5)),
  legal:d('Legal balance',p('scales',0,0,1.5)),
  commerce:d('Pickup storefront',p('booth',-.2,0,1.3),p('package',.7,.35,.7)),
  hardware:d('Compute accelerator',p('chip',0,0,1.9)),
  data:d('Storage rack',p('rack',0,0,1.4)),
  api:d('Server gateway with interface terminal',p('rack',-.4,0,1.1),p('terminal',.5,.25,.8)),
  opensource:d('Shared code and open reference',p('code',-.2,-.1,1.2),p('book',.4,.5)),
  'auto-research':d('Automated laboratory',p('arm',-.6,-.2,1.1),p('tubes',.43,.25,1.2)),
  'self-improve':d('Self-tuning hardware test rig',p('chip',-.2,.2,1.3),p('arm',.5,-.3,.9)),
};

export function recipeDesignFor(a:string,b:string):ProductDesign|undefined {
  const id=recipeKey(a,b), design=recipeDesigns[id];
  if(!design && findRecipe(a,b)) throw new Error(`Missing recipe visual: ${id}`);
  return design;
}
export function primitiveDesignFor(id:string):ProductDesign {
  const design=primitiveDesigns[id];
  if(!design) throw new Error(`Missing primitive visual: ${id}`);
  return design;
}
