import { normalizeLook } from '../../simulation/look';
import type { CharacterLook } from '../../simulation/types';

export interface FounderReference {
  name: string;
  role: string;
  look: CharacterLook;
}

export const referenceLooks: FounderReference[] = [
  {
    name: 'Steve Jobs',
    role: 'Product vision',
    look: normalizeLook({
      skin: '#f2c8a2',
      hair: '#8c929a',
      hairStyle: 'balding',
      top: '#222224',
      topId: 'turtleneck',
      pants: '#55708c',
      pantsId: 'jeans',
      shoes: '#dedede',
      shoesId: 'sneakers',
      glassesId: 'round',
      beard: true,
      beardColor: '#8c929a',
      body: 'average',
      archetype: 'founder',
    }),
  },
  {
    name: 'Mark Zuckerberg',
    role: 'Builds relentlessly',
    look: normalizeLook({
      skin: '#f3d1b0',
      hair: '#5a3d28',
      hairStyle: 'curly',
      top: '#72777f',
      topId: 'tee',
      pants: '#456588',
      pantsId: 'jeans',
      shoes: '#f0f2f5',
      shoesId: 'sneakers',
      glassesId: 'none',
      beard: false,
      body: 'average',
      archetype: 'founder',
    }),
  },
  {
    name: 'Bill Gates',
    role: 'Platform thinker',
    look: normalizeLook({
      skin: '#f3d1b0',
      hair: '#5c4a3e',
      hairStyle: 'side-part',
      top: '#3b689a',
      topId: 'sweater',
      pants: '#b59a7a',
      pantsId: 'trousers',
      shoes: '#4a3325',
      shoesId: 'dress',
      glassesId: 'rect',
      beard: false,
      body: 'average',
      archetype: 'founder',
    }),
  },
  {
    name: 'Sam Altman',
    role: 'Capital + AI',
    look: normalizeLook({
      skin: '#f3d1b0',
      hair: '#4d3728',
      hairStyle: 'textured',
      top: '#3d67a2',
      topId: 'sweater',
      pants: '#303338',
      pantsId: 'trousers',
      shoes: '#f0f2f5',
      shoesId: 'sneakers',
      glassesId: 'none',
      beard: false,
      body: 'average',
      archetype: 'founder',
    }),
  },
  {
    name: 'Jensen Huang',
    role: 'More compute',
    look: normalizeLook({
      skin: '#e0b184',
      hair: '#9ca2aa',
      hairStyle: 'swept',
      top: '#1c1d1f',
      topId: 'jacket',
      pants: '#2d3034',
      pantsId: 'jeans',
      shoes: '#18191b',
      shoesId: 'dress',
      glassesId: 'rect',
      beard: false,
      body: 'average',
      archetype: 'founder',
    }),
  },
  {
    name: 'Elon Musk',
    role: 'Moonshot operator',
    look: normalizeLook({
      skin: '#f3d1b0',
      hair: '#5a3f2d',
      hairStyle: 'messy',
      top: '#282c30',
      topId: 'blazer',
      pants: '#2c3035',
      pantsId: 'trousers',
      shoes: '#18191b',
      shoesId: 'dress',
      glassesId: 'none',
      beard: false,
      body: 'average',
      archetype: 'founder',
    }),
  },
  {
    name: 'Reed Hastings',
    role: 'Company culture',
    look: normalizeLook({
      skin: '#f3d1b0',
      hair: '#404449',
      hairStyle: 'beanie',
      top: '#222326',
      topId: 'turtleneck',
      pants: '#5c6e5a',
      pantsId: 'trousers',
      shoes: '#eef0f3',
      shoesId: 'sneakers',
      glassesId: 'none',
      beard: true,
      beardColor: '#9da2a8',
      body: 'average',
      archetype: 'founder',
    }),
  },
  {
    name: 'Jeff Bezos',
    role: 'Operates at scale',
    look: normalizeLook({
      skin: '#f0d5b8',
      hair: '#1a1a1a',
      hairStyle: 'bald',
      top: '#2d4972',
      topId: 'blazer',
      pants: '#c0a98c',
      pantsId: 'trousers',
      shoes: '#523b2b',
      shoesId: 'dress',
      glassesId: 'none',
      beard: false,
      body: 'average',
      archetype: 'founder',
    }),
  },
];
