import type { MarketSegmentDefinition, MarketTemplate } from "./types";

export const MARKET_SEGMENTS: Record<string, MarketSegmentDefinition> = {
  // Developer Ecosystem
  developers: {
    id: "developers",
    name: "Developers",
    verticals: ["developer", "consumer"],
    value: 2,
    resistance: 2,
    load: 2,
    trait: "early_adopter",
    productAffinities: { code: 2, chat: 1, api: 1, search: 1 },
    userPotential: 18000,
  },
  opensource: {
    id: "opensource",
    name: "Open Source",
    verticals: ["developer"],
    value: 1,
    resistance: 2,
    load: 1,
    trait: "community_driven",
    productAffinities: { code: 2, opensource: 3 },
    userPotential: 25000,
  },
  startups: {
    id: "startups",
    name: "Startups",
    verticals: ["developer", "enterprise"],
    value: 3,
    resistance: 2,
    load: 2,
    trait: "platform_hub",
    productAffinities: { code: 1, workflow: 2, chat: 1 },
    userPotential: 12000,
  },
  dev_teams: {
    id: "dev_teams",
    name: "Dev Teams",
    verticals: ["developer", "enterprise"],
    value: 3,
    resistance: 3,
    load: 2,
    trait: "platform_hub",
    productAffinities: { code: 2, agent: 1, workflow: 1 },
    userPotential: 8000,
  },
  agencies: {
    id: "agencies",
    name: "Agencies",
    verticals: ["developer", "enterprise", "media"],
    value: 3,
    resistance: 3,
    load: 3,
    trait: "high_value",
    productAffinities: { writing: 2, image: 2, video: 2, code: 1 },
    userPotential: 6000,
  },
  enterprise: {
    id: "enterprise",
    name: "Enterprise",
    verticals: ["enterprise", "developer", "finance", "legal"],
    value: 5,
    resistance: 5,
    load: 4,
    trait: "enterprise",
    productAffinities: { workflow: 2, security: 2, retrieval: 2, reasoning: 1 },
    userPotential: 2000,
  },
  universities: {
    id: "universities",
    name: "Universities",
    verticals: ["developer", "education", "science"],
    value: 1,
    resistance: 2,
    load: 1,
    trait: "early_adopter",
    productAffinities: { education: 2, search: 1, writing: 1 },
    userPotential: 22000,
  },
  creators: {
    id: "creators",
    name: "Creators",
    verticals: ["consumer", "media"],
    value: 2,
    resistance: 2,
    load: 2,
    trait: "viral",
    productAffinities: { video: 2, image: 2, writing: 1, voice: 1 },
    userPotential: 28000,
  },

  // Consumer & Social
  students: {
    id: "students",
    name: "Students",
    verticals: ["consumer", "education"],
    value: 1,
    resistance: 1,
    load: 1,
    trait: "early_adopter",
    productAffinities: { chat: 2, writing: 2, education: 2 },
    userPotential: 35000,
  },
  gamers: {
    id: "gamers",
    name: "Gamers",
    verticals: ["consumer"],
    value: 2,
    resistance: 2,
    load: 2,
    trait: "community_driven",
    productAffinities: { avatar: 2, voice: 1, simulation: 2 },
    userPotential: 24000,
  },
  young_professionals: {
    id: "young_professionals",
    name: "Young Professionals",
    verticals: ["consumer", "enterprise"],
    value: 3,
    resistance: 2,
    load: 2,
    trait: "platform_hub",
    productAffinities: { writing: 2, search: 1, memory: 1 },
    userPotential: 16000,
  },
  consumers: {
    id: "consumers",
    name: "General Consumers",
    verticals: ["consumer"],
    value: 2,
    resistance: 3,
    load: 2,
    trait: "viral",
    productAffinities: { chat: 2, search: 2, social: 2 },
    userPotential: 40000,
  },
  parents: {
    id: "parents",
    name: "Parents & Families",
    verticals: ["consumer", "education"],
    value: 3,
    resistance: 3,
    load: 2,
    trait: "high_value",
    productAffinities: { education: 2, memory: 1, safety: 2 },
    userPotential: 14000,
  },
  online_communities: {
    id: "online_communities",
    name: "Online Communities",
    verticals: ["consumer"],
    value: 2,
    resistance: 2,
    load: 1,
    trait: "viral",
    productAffinities: { social: 3, chat: 1, avatar: 1 },
    userPotential: 30000,
  },

  // B2B & Enterprise Workflows
  solo_founders: {
    id: "solo_founders",
    name: "Solo Founders",
    verticals: ["enterprise", "developer"],
    value: 2,
    resistance: 1,
    load: 1,
    trait: "early_adopter",
    productAffinities: { agent: 2, workflow: 2, code: 1 },
    userPotential: 15000,
  },
  smb: {
    id: "smb",
    name: "SMB Businesses",
    verticals: ["enterprise", "commerce"],
    value: 3,
    resistance: 3,
    load: 2,
    trait: "high_value",
    productAffinities: { workflow: 2, commerce: 2, analytics: 1 },
    userPotential: 10000,
  },
  mid_market: {
    id: "mid_market",
    name: "Mid-Market",
    verticals: ["enterprise"],
    value: 4,
    resistance: 4,
    load: 3,
    trait: "platform_hub",
    productAffinities: { agent: 1, workflow: 2, retrieval: 1 },
    userPotential: 5000,
  },
  revops: {
    id: "revops",
    name: "RevOps Teams",
    verticals: ["enterprise", "finance"],
    value: 4,
    resistance: 4,
    load: 3,
    trait: "regulated",
    productAffinities: { analytics: 2, workflow: 2, finance: 1 },
    userPotential: 4000,
  },

  // Media & Creative
  influencers: {
    id: "influencers",
    name: "Influencers",
    verticals: ["media", "consumer"],
    value: 3,
    resistance: 2,
    load: 2,
    trait: "viral",
    productAffinities: { video: 2, image: 2, avatar: 2 },
    userPotential: 20000,
  },
  social_teams: {
    id: "social_teams",
    name: "Social Teams",
    verticals: ["media", "enterprise"],
    value: 3,
    resistance: 2,
    load: 2,
    trait: "platform_hub",
    productAffinities: { social: 2, video: 1, writing: 1 },
    userPotential: 11000,
  },
  marketing_teams: {
    id: "marketing_teams",
    name: "Marketing Teams",
    verticals: ["media", "enterprise"],
    value: 4,
    resistance: 3,
    load: 3,
    trait: "high_value",
    productAffinities: { writing: 2, analytics: 2, ads: 2 },
    userPotential: 7000,
  },
  studios: {
    id: "studios",
    name: "Production Studios",
    verticals: ["media"],
    value: 5,
    resistance: 5,
    load: 4,
    trait: "enterprise",
    productAffinities: { video: 3, avatar: 2, image: 2 },
    userPotential: 1500,
  },

  // Science & Life Sciences
  academic_labs: {
    id: "academic_labs",
    name: "Academic Labs",
    verticals: ["science", "biotech"],
    value: 2,
    resistance: 2,
    load: 1,
    trait: "early_adopter",
    productAffinities: { science: 3, reasoning: 2 },
    userPotential: 9000,
  },
  biotech_startups: {
    id: "biotech_startups",
    name: "Biotech Startups",
    verticals: ["biotech", "science"],
    value: 3,
    resistance: 3,
    load: 2,
    trait: "platform_hub",
    productAffinities: { biology: 3, science: 2 },
    userPotential: 6000,
  },
  hospitals: {
    id: "hospitals",
    name: "Hospitals & Clinics",
    verticals: ["health", "biotech"],
    value: 4,
    resistance: 5,
    load: 3,
    trait: "regulated",
    productAffinities: { health: 3, retrieval: 2 },
    userPotential: 3500,
  },
  mid_pharma: {
    id: "mid_pharma",
    name: "Mid Pharma",
    verticals: ["biotech", "science"],
    value: 4,
    resistance: 4,
    load: 3,
    trait: "high_value",
    productAffinities: { biology: 2, reasoning: 2 },
    userPotential: 2500,
  },
  global_pharma: {
    id: "global_pharma",
    name: "Global Pharma",
    verticals: ["biotech", "health"],
    value: 5,
    resistance: 6,
    load: 4,
    trait: "enterprise",
    productAffinities: { biology: 3, safety: 2 },
    userPotential: 1000,
  },
  gov_labs: {
    id: "gov_labs",
    name: "Government Labs",
    verticals: ["science", "defense"],
    value: 4,
    resistance: 5,
    load: 3,
    trait: "regulated",
    productAffinities: { science: 2, defense: 2 },
    userPotential: 2000,
  },

  // Defense & Robotics
  robotics_startups: {
    id: "robotics_startups",
    name: "Robotics Startups",
    verticals: ["robotics", "hardware"],
    value: 3,
    resistance: 2,
    load: 2,
    trait: "early_adopter",
    productAffinities: { robotics: 3, agent: 2 },
    userPotential: 7000,
  },
  commercial_fleet: {
    id: "commercial_fleet",
    name: "Commercial Fleets",
    verticals: ["robotics", "commerce"],
    value: 4,
    resistance: 4,
    load: 3,
    trait: "platform_hub",
    productAffinities: { robotics: 2, vision: 2 },
    userPotential: 4000,
  },
  industrial_giants: {
    id: "industrial_giants",
    name: "Industrial Giants",
    verticals: ["robotics", "hardware"],
    value: 5,
    resistance: 5,
    load: 4,
    trait: "high_value",
    productAffinities: { robotics: 2, world_model: 2 },
    userPotential: 1500,
  },
  defense_contractors: {
    id: "defense_contractors",
    name: "Defense Contractors",
    verticals: ["defense"],
    value: 5,
    resistance: 6,
    load: 4,
    trait: "enterprise",
    productAffinities: { defense: 3, security: 2 },
    userPotential: 1200,
  },
  municipalities: {
    id: "municipalities",
    name: "Municipalities",
    verticals: ["robotics", "defense"],
    value: 3,
    resistance: 4,
    load: 2,
    trait: "regulated",
    productAffinities: { vision: 2, security: 1 },
    userPotential: 5000,
  },
};

// Hand-authored graph templates with normalized coordinates (viewBox 600 x 420)
export const MARKET_TEMPLATES: Record<string, MarketTemplate> = {
  // Tutorial & Default Developer Graph
  tutorial: {
    id: "tutorial",
    name: "Developer Ecosystem",
    verticals: ["developer", "consumer", "generic"],
    nodes: [
      { id: "n_devs", segmentId: "developers", x: 90, y: 310 },
      { id: "n_creators", segmentId: "creators", x: 90, y: 110 },
      { id: "n_unis", segmentId: "universities", x: 200, y: 360 },
      { id: "n_startups", segmentId: "startups", x: 260, y: 210 },
      { id: "n_agencies", segmentId: "agencies", x: 420, y: 100 },
      { id: "n_teams", segmentId: "dev_teams", x: 390, y: 320 },
      { id: "n_enterprise", segmentId: "enterprise", x: 520, y: 210 },
    ],
    edges: [
      { a: "n_devs", b: "n_startups" },
      { a: "n_devs", b: "n_unis" },
      { a: "n_creators", b: "n_startups" },
      { a: "n_creators", b: "n_agencies" },
      { a: "n_unis", b: "n_teams" },
      { a: "n_startups", b: "n_teams" },
      { a: "n_startups", b: "n_agencies" },
      { a: "n_agencies", b: "n_enterprise" },
      { a: "n_teams", b: "n_enterprise" },
    ],
    defaultPlayerBeachhead: "n_devs",
    defaultRivalBeachhead: "n_enterprise",
  },

  developer: {
    id: "developer",
    name: "Developer & Engineering Tools",
    verticals: ["developer"],
    nodes: [
      { id: "n_devs", segmentId: "developers", x: 80, y: 300 },
      { id: "n_oss", segmentId: "opensource", x: 80, y: 130 },
      { id: "n_creators", segmentId: "creators", x: 210, y: 70 },
      { id: "n_unis", segmentId: "universities", x: 200, y: 360 },
      { id: "n_startups", segmentId: "startups", x: 270, y: 210 },
      { id: "n_teams", segmentId: "dev_teams", x: 400, y: 290 },
      { id: "n_agencies", segmentId: "agencies", x: 410, y: 120 },
      { id: "n_enterprise", segmentId: "enterprise", x: 530, y: 210 },
    ],
    edges: [
      { a: "n_devs", b: "n_oss" },
      { a: "n_devs", b: "n_unis" },
      { a: "n_devs", b: "n_startups" },
      { a: "n_oss", b: "n_creators" },
      { a: "n_oss", b: "n_startups" },
      { a: "n_creators", b: "n_agencies" },
      { a: "n_unis", b: "n_teams" },
      { a: "n_startups", b: "n_teams" },
      { a: "n_startups", b: "n_agencies" },
      { a: "n_agencies", b: "n_enterprise" },
      { a: "n_teams", b: "n_enterprise" },
    ],
    defaultPlayerBeachhead: "n_devs",
    defaultRivalBeachhead: "n_enterprise",
  },

  consumer: {
    id: "consumer",
    name: "Consumer & Social Audience",
    verticals: ["consumer"],
    nodes: [
      { id: "n_students", segmentId: "students", x: 90, y: 310 },
      { id: "n_creators", segmentId: "creators", x: 90, y: 110 },
      { id: "n_comm", segmentId: "online_communities", x: 250, y: 90 },
      { id: "n_gamers", segmentId: "gamers", x: 250, y: 320 },
      { id: "n_pro", segmentId: "young_professionals", x: 370, y: 200 },
      { id: "n_parents", segmentId: "parents", x: 490, y: 110 },
      { id: "n_consumers", segmentId: "consumers", x: 510, y: 300 },
    ],
    edges: [
      { a: "n_students", b: "n_gamers" },
      { a: "n_students", b: "n_creators" },
      { a: "n_creators", b: "n_comm" },
      { a: "n_gamers", b: "n_pro" },
      { a: "n_comm", b: "n_pro" },
      { a: "n_comm", b: "n_parents" },
      { a: "n_pro", b: "n_consumers" },
      { a: "n_parents", b: "n_consumers" },
      { a: "n_gamers", b: "n_consumers" },
    ],
    defaultPlayerBeachhead: "n_students",
    defaultRivalBeachhead: "n_consumers",
  },

  enterprise: {
    id: "enterprise",
    name: "Enterprise & Operations",
    verticals: ["enterprise", "finance", "legal"],
    nodes: [
      { id: "n_founders", segmentId: "solo_founders", x: 90, y: 210 },
      { id: "n_startups", segmentId: "startups", x: 220, y: 110 },
      { id: "n_smb", segmentId: "smb", x: 220, y: 310 },
      { id: "n_mid", segmentId: "mid_market", x: 370, y: 210 },
      { id: "n_agencies", segmentId: "agencies", x: 370, y: 70 },
      { id: "n_revops", segmentId: "revops", x: 380, y: 350 },
      { id: "n_enterprise", segmentId: "enterprise", x: 515, y: 210 },
    ],
    edges: [
      { a: "n_founders", b: "n_startups" },
      { a: "n_founders", b: "n_smb" },
      { a: "n_startups", b: "n_agencies" },
      { a: "n_startups", b: "n_mid" },
      { a: "n_smb", b: "n_mid" },
      { a: "n_smb", b: "n_revops" },
      { a: "n_agencies", b: "n_enterprise" },
      { a: "n_mid", b: "n_enterprise" },
      { a: "n_revops", b: "n_enterprise" },
    ],
    defaultPlayerBeachhead: "n_founders",
    defaultRivalBeachhead: "n_enterprise",
  },

  media: {
    id: "media",
    name: "Media & Production",
    verticals: ["media"],
    nodes: [
      { id: "n_creators", segmentId: "creators", x: 80, y: 290 },
      { id: "n_inf", segmentId: "influencers", x: 100, y: 110 },
      { id: "n_social", segmentId: "social_teams", x: 250, y: 200 },
      { id: "n_consumers", segmentId: "consumers", x: 240, y: 350 },
      { id: "n_agencies", segmentId: "agencies", x: 390, y: 110 },
      { id: "n_marketing", segmentId: "marketing_teams", x: 400, y: 300 },
      { id: "n_studios", segmentId: "studios", x: 520, y: 200 },
    ],
    edges: [
      { a: "n_creators", b: "n_inf" },
      { a: "n_creators", b: "n_consumers" },
      { a: "n_creators", b: "n_social" },
      { a: "n_inf", b: "n_social" },
      { a: "n_social", b: "n_agencies" },
      { a: "n_social", b: "n_marketing" },
      { a: "n_consumers", b: "n_marketing" },
      { a: "n_agencies", b: "n_studios" },
      { a: "n_marketing", b: "n_studios" },
    ],
    defaultPlayerBeachhead: "n_creators",
    defaultRivalBeachhead: "n_studios",
  },

  science: {
    id: "science",
    name: "Scientific & Clinical Research",
    verticals: ["science", "biotech", "health"],
    nodes: [
      { id: "n_acad", segmentId: "academic_labs", x: 85, y: 120 },
      { id: "n_unis", segmentId: "universities", x: 90, y: 300 },
      { id: "n_biotech", segmentId: "biotech_startups", x: 240, y: 200 },
      { id: "n_gov", segmentId: "gov_labs", x: 370, y: 90 },
      { id: "n_hospitals", segmentId: "hospitals", x: 360, y: 320 },
      { id: "n_mid_pharma", segmentId: "mid_pharma", x: 420, y: 200 },
      { id: "n_global_pharma", segmentId: "global_pharma", x: 530, y: 200 },
    ],
    edges: [
      { a: "n_acad", b: "n_unis" },
      { a: "n_acad", b: "n_biotech" },
      { a: "n_unis", b: "n_biotech" },
      { a: "n_biotech", b: "n_gov" },
      { a: "n_biotech", b: "n_hospitals" },
      { a: "n_biotech", b: "n_mid_pharma" },
      { a: "n_gov", b: "n_global_pharma" },
      { a: "n_hospitals", b: "n_mid_pharma" },
      { a: "n_mid_pharma", b: "n_global_pharma" },
    ],
    defaultPlayerBeachhead: "n_acad",
    defaultRivalBeachhead: "n_global_pharma",
  },

  robotics: {
    id: "robotics",
    name: "Physical & Robotics Infrastructure",
    verticals: ["robotics", "hardware", "defense"],
    nodes: [
      { id: "n_startups", segmentId: "robotics_startups", x: 90, y: 210 },
      { id: "n_fleet", segmentId: "commercial_fleet", x: 230, y: 110 },
      { id: "n_muni", segmentId: "municipalities", x: 230, y: 310 },
      { id: "n_ind", segmentId: "industrial_giants", x: 380, y: 120 },
      { id: "n_def", segmentId: "defense_contractors", x: 515, y: 210 },
      { id: "n_unis", segmentId: "universities", x: 370, y: 320 },
    ],
    edges: [
      { a: "n_startups", b: "n_fleet" },
      { a: "n_startups", b: "n_muni" },
      { a: "n_fleet", b: "n_ind" },
      { a: "n_muni", b: "n_unis" },
      { a: "n_ind", b: "n_def" },
      { a: "n_unis", b: "n_def" },
      { a: "n_muni", b: "n_ind" },
    ],
    defaultPlayerBeachhead: "n_startups",
    defaultRivalBeachhead: "n_def",
  },
};

const VERTICAL_TEMPLATE_MAP: Record<string, string> = {
  developer: "developer",
  consumer: "consumer",
  education: "consumer",
  enterprise: "enterprise",
  finance: "enterprise",
  legal: "enterprise",
  media: "media",
  science: "science",
  biotech: "science",
  health: "science",
  robotics: "robotics",
  hardware: "robotics",
  defense: "robotics",
};

export function selectTemplateForProduct(
  vertical: string,
  combo: [string, string],
  firstMarket: boolean,
): MarketTemplate {
  if (firstMarket) {
    return MARKET_TEMPLATES.tutorial!;
  }
  const mapped = VERTICAL_TEMPLATE_MAP[vertical];
  if (mapped && MARKET_TEMPLATES[mapped]) {
    return MARKET_TEMPLATES[mapped]!;
  }
  if (MARKET_TEMPLATES[vertical]) {
    return MARKET_TEMPLATES[vertical]!;
  }
  if (combo.includes("code") || combo.includes("api")) {
    return MARKET_TEMPLATES.developer!;
  }
  if (combo.includes("video") || combo.includes("image") || combo.includes("avatar")) {
    return MARKET_TEMPLATES.media!;
  }
  if (combo.includes("agent") || combo.includes("workflow") || combo.includes("analytics")) {
    return MARKET_TEMPLATES.enterprise!;
  }
  if (combo.includes("science") || combo.includes("biology") || combo.includes("health")) {
    return MARKET_TEMPLATES.science!;
  }
  if (combo.includes("robotics") || combo.includes("hardware") || combo.includes("defense")) {
    return MARKET_TEMPLATES.robotics!;
  }
  return MARKET_TEMPLATES.consumer ?? MARKET_TEMPLATES.tutorial!;
}
